### ISSUE TITLE
AMP to new Alfresco version

### ISSUE THREAD

**Issue by marcokonsultex** [EisenVault/Alfresco-Autocad-Viewer#2]
Good afternoon.

I'm trying to use this amp to view CAD documents in Alfresco and I see that it points to versions 5.1 and 5.2. Has there been any testing or update for the latest versions of Alfresco? I'm using 2023.2.1.

Thanks

**Comment by vipulswarup** [comment]
Hi.

Thanks for your email.
Afraid this addon doesn’t work well any more. We are experimenting with
using AutoCad’s own API to display cad files in Alfresco share, but we
don’t have an addon for that yet.

Thanks
Vipul

**Comment by marcokonsultex** [comment]
Thanks for your feedback.

I think that currently only Formtek is available for this use.
